### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by giveup** [SciresM/boot9strap#23]
devkit r47
boot9strap https://github.com/SciresM/boot9strap/commit/632a441621a1b6c19dcbc207c54de4b2f97856b4
pycryptodome (3.4.7)

> arm-none-eabi-objcopy -S -O binary build/arm11.elf out/arm11.bin
Traceback (most recent call last):
  File "build_boot9strap_firm.py", line 2, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
make: *** [boot9strap] Error 1

**Comment by Derek1199** [comment]
Do you have armips? You know that's required...right?

**Comment by giveup** [comment]
@Derek1199 Yes. armips https://github.com/Kingcom/armips/commit/07853e5bbdab1914168a00c1b736d2f7cd898942

**Comment by Derek1199** [comment]
Try `pip install --upgrade pycryptodome`

**Comment by Derek1199** [comment]
Also, try using latest commit of ctrulib.

**Comment by giveup** [comment]
@Derek1199 Thank you for the help. Every lib is up to date.

**Comment by Derek1199** [comment]
I forgot to ask. What OS are you using?

**Comment by giveup** [comment]
@Derek1199 
macOS 10.12.6  
Python 3.6.2

**Comment by Derek1199** [comment]
Then I don't know. I'll ask someone.

**Comment by Nemris** [comment]
@giveup

PyCryptodome may have been installed as `Cryptodome` and not `Crypto`, as per the notes concerning version 3.4.1 (and upper), available [here](https://pycryptodome.readthedocs.io/en/latest/src/changelog.html#august-2017). Try replacing `from Crypto.Cipher import AES` with `from Cryptodome.Cipher import AES`.

**Comment by giveup** [comment]
@DMSalesman Not working. same error.

**Comment by urherenow** [comment]
I personally haven't had much luck with Python 3.6. I have both 3.6 and 2.7 installed and just change my path whenever the need arises. I suggest installing Python 2.7 in a custom directory (ie. c:\Python27), change the python36 path to python27 in your environment variables, then install pycrypto, and this will build with no issues.

**Comment by ihaveamac** [comment]
make sure you're installing pycryptodome for the correct version that's being used. it sounds like it's installing for the wrong thing.
```
pip3 install pycryptodome
python3 build_boot9strap_firm.py

# or alternatively...
python3 -m pip install pycryptodome
```
replace 3 with 2 if you're using py2.

**Comment by giveup** [comment]
@ihaveamac 
`python3 boot9strap/build_boot9strap_firm.py 
Traceback (most recent call last):
  File "/boot9strap/build_boot9strap_firm.py", line 2, in <module>
    from Crypto.Cipher import AES
ImportError: cannot import name 'AES'`
I edit Makefile and replace python with python2,It works.Thank you for your help.

**Comment by urherenow** [comment]
I neither have python2 nor python3. I only have python.exe in both my Python27 and Python36 directories. With Python36 in my path, I installed pip3 install pycryptodome with no errors, but I still get the above error about "No module named Crypto". What am I doing wrong? Again, I have no issues with Python27 as my path with pycrypto installed.

**Comment by Derek1199** [comment]
Do ``pip install pycryptodome`` @urherenow

**Comment by urherenow** [comment]
Actually, I figured this out already. With Python3, pycryptodome is all I EVER tried using and it never worked. I had to use 

pip3 install cryptography
